rvm:
- 2.4.2
bundler_args: "--without debug development"
cache: bundler
before_script:
- cp .sample.env .env
- export SECRET_KEY_BASE="$(bundle exec rake secret)"
- cp config/database.travis.yml config/database.yml
- psql -c 'create database hours_test' -U postgres
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
